INSERT INTO tags (name) VALUES 
('Technology'),
('Programming'),
('Web Development'),
('Mobile Development'),
('Software Engineering'),
('Artificial Intelligence'),
('Cybersecurity'),
('Data Science'),
('Business'),
('Productivity'),
('Education'),
('Health'),
('Travel'),
('Food'),
('Books'),
('Movies'),
('Gaming'),
('Science'),
('Tutorial'),
('Opinion');